name: Generate Snake Contribution Graph

on:
  schedule:
    - cron: "0 0 * * *"  # every day at midnight
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Generate Snake SVG
        uses: Platane/snk@v3
        with:
          github_user_name: urvalkheni
          outputs: |
            dist/github-snake.svg

      - name: Commit and Push SVG
        uses: EndBug/add-and-commit@v9
        with:
          message: "Generated Snake Contribution Graph"
          add: "dist/github-snake.svg"
